serenity.project.name = CBP PSPD Automated Test Suite Execution Summary

enable.markdown=story,narrative,scenario
serenity.outputDirectory = ./target/serenity-reports
serenity.console.colors=true
serenity.test.root=features
serenity.add.context.tag=true

#How long does Serenity wait for elements that are not present on the screen to load
webdriver.timeouts.implicitlywait=15000
webdriver.wait.for.timeout=15000
webdriver.chrome.silentOutput=true

serenity.dry.run=false
serenity.logging=NORMAL

serenity.take.screenshots = AFTER_EACH_STEP

ACCEPT_INSECURE_CERTIFICATES=true